apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: gitops-app-dev
namePrefix: dev-
# commonLabels:
#   env: dev
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: gitops-app
    env: dev
images:
- name: gitops-app
  newName: zionn1002/gitops-app
  newTag: sha-b9ccd4c

replicas:
- count: 1
  name: gitops-app
