apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: gitops-app-prod
namePrefix: prod-
# commonLabels:
#   env: prod
labels:
  - pairs:
      app: gitops-app
      env: prod
    includeSelectors: true
    includeTemplates: true
images:
  - name: gitops-app
    newName: zionn1002/gitops-app
    newTag: latest

replicas:
  - name: gitops-app
    count: 3
