# argocd/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-project
  namespace: argocd
spec:
  description: "gitops-app 프로젝트"
  sourceRepos:
    - "https://github.com/zionn1002/gitops-config"
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: "ops-app1-*"
    - server: "https://kubernetes.default.svc"
      namespace: "ops-app2-*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "gateway.networking.k8s.io"
      kind: GatewayClass
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
