# infra/prometheus/servicemonitor-ops-app1.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ops-app1
  namespace: monitoring # Prometheus와 같은 네임스페이스
  labels:
    release: kube-prometheus-stack # 설치한 Helm Release 이름
spec:
  namespaceSelector:
    matchNames:
      - ops-app1-eks-dev
  selector:
    matchLabels:
      app.kubernetes.io/name: ops-app1 # base/service.yaml의 라벨과 일치
  endpoints:
    - port: http # Service에서 정의한 포트 name
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
