# infra/prometheus/servicemonitor-ops-app2.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ops-app2
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - ops-app2-eks-dev
  selector:
    matchLabels:
      app.kubernetes.io/name: ops-app2
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
