apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ops-app1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ops-app1
    spec:
      containers:
        - name: app
          image: ops-app1
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: ops-app1-config
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
