# apps/ops-app2/overlays/eks-dev/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ops-app2-secrets
  namespace: ops-app2-eks-dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: ops-app2-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: /ops-platform/dev/api-key
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /ops-platform/dev/db-password
